delete from PRDDBS1.TPY_PAY_INSTR WHERE CASE_KEY = 1010619 
delete from PRDDBS1.TCS_CSSA WHERE CASE_KEY = 1010619 
delete from PRDDBS1.TMS_COMM WHERE CASE_KEY = 1010619 
--------------------------------------------------
delete from PRDDBS1.TPY_PAY_INSTR where CASE_KEY=  and GRT_TYPE=' ' and PAY_TYPE=' ' and FR_DATE=' ' and TO_DATE=' ' and REC_STS=' '
delete from PRDDBS1.TCS_CSSA where CASE_KEY= 
delete from PRDDBS1.TMS_COMM where CASE_KEY=  and CRE_DATE=' ' and LAST_UPD_TS=' '
--------------------------------------------------
SELECT * FROM PRDDBS1.TPY_PAY_INSTR WHERE CASE_KEY = 1010619 ORDER BY CASE_KEY, GRT_TYPE, PAY_TYPE, FR_DATE, TO_DATE, REC_STS 
SELECT * FROM PRDDBS1.TCS_CSSA WHERE CASE_KEY = 1010619 
SELECT * FROM PRDDBS1.TMS_COMM WHERE CASE_KEY = 1010619 ORDER BY CASE_KEY, CRE_DATE 