<dataset>
  <table name="ARC_SURCHINCREMENTAL">
    <column>TRAK_ROWID</column>
    <column>SURCHARGE_CODE</column>
    <column>TIME_FROM</column>
    <column>TIME_UNTIL</column>
    <column>FIXED_AMOUNT</column>
    <column>ROOM_TYPE_CODE</column>
    <column>AMOUNT_PER_EXTRA_BLOCK</column>
    <column>FIXED_AMOUNT_TIME_BLOCK</column>
    <column>MINUTES_PER_EXTRA_BLOCK</column>
    <column>EFFECTIVE_DATE_FROM</column>
    <column>EFFECTIVE_DATE_TO</column>
    <column>CREATE_DATE</column>
    <column>UPDATE_DATE</column>
    <column>CREATE_BY</column>
    <column>UPDATE_BY</column>
  </table>
</dataset>
