delete from PRDDBS1.TMS_COMM WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TPY_PAY_AUTH WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TCS_BANK_ACC WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TPY_CHG_OF_ACC WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TPY_HIST WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TAS_PROF_HIST WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TAS_ELG_PERD WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TCS_TP_DTL WHERE CASE_KEY = 4468919
delete from PRDDBS1.TCT_CUST WHERE CUST_KEY = 3731257 OR CUST_KEY = 3735422 OR CUST_KEY = 3735424 
delete from PRDDBS1.TCT_CUST_DTL WHERE CUST_KEY = 3731257 OR CUST_KEY = 3735422 OR CUST_KEY = 3735424 
TMS_PT_GEN_SDL:noWhereClauseFound
delete from PRDDBS1.TPY_PAY_INSTR WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TMS_PAY_EST WHERE CASE_KEY = 4468919 
delete from PRDDBS1.TCS_CSSA WHERE CASE_KEY = 4468919
--------------------------------------------------
delete from PRDDBS1.TMS_COMM where CASE_KEY=  and CRE_DATE=' ' and LAST_UPD_TS=' '
delete from PRDDBS1.TPY_PAY_AUTH where CASE_KEY=  and REC_STS=' ' and FR_DATE=' '
delete from PRDDBS1.TCS_BANK_ACC where CASE_KEY=  and SEQ_NUM= 
delete from PRDDBS1.TPY_CHG_OF_ACC where CASE_KEY=  and NEW_BANK_CODE=' ' and NEW_BRN_CODE=' ' and NEW_ACC_NUM=' ' and PAY_DATE=' '
delete from PRDDBS1.TPY_HIST where CASE_KEY=  and CRE_TS=' ' and FR_DATE=' ' and TO_DATE=' ' and TXN_DATE=' ' and PAY_TYPE=' ' and PAY_MTHD=' '
delete from PRDDBS1.TAS_PROF_HIST where CASE_KEY=  and CRE_TS=' '
delete from PRDDBS1.TAS_ELG_PERD where CASE_KEY=  and CUST_KEY=  and REC_STS=' ' and FR_DATE=' '
delete from PRDDBS1.TCS_TP_DTL where CASE_KEY=  and TP_TYPE=' '
delete from PRDDBS1.TCT_CUST where CUST_KEY= 
delete from PRDDBS1.TCT_CUST_DTL where CUST_KEY= 
delete from PRDDBS1.TMS_PT_GEN_SDL where SCHM_TYPE=' ' and YR=  and MTH=  and PAY_DAY=  and HSBC_GRP_IND=' '
delete from PRDDBS1.TPY_PAY_INSTR where CASE_KEY=  and GRT_TYPE=' ' and PAY_TYPE=' ' and FR_DATE=' ' and TO_DATE=' ' and REC_STS=' '
delete from PRDDBS1.TMS_PAY_EST where CASE_KEY=  and GRT_TYPE=' ' and PAY_DATE=' ' and FR_DATE=' '
delete from PRDDBS1.TCS_CSSA where CASE_KEY= 
--------------------------------------------------
SELECT * FROM PRDDBS1.TMS_COMM WHERE CASE_KEY = 4468919 ORDER BY CRE_DATE
SELECT * FROM PRDDBS1.TPY_PAY_AUTH WHERE CASE_KEY = 4468919 ORDER BY REC_STS, FR_DATE 
SELECT * FROM PRDDBS1.TCS_BANK_ACC WHERE CASE_KEY = 4468919 ORDER BY SEQ_NUM 
SELECT * FROM PRDDBS1.TPY_CHG_OF_ACC WHERE CASE_KEY = 4468919 ORDER BY NEW_BANK_CODE, NEW_BRN_CODE, NEW_ACC_NUM, PAY_DATE 
SELECT * FROM PRDDBS1.TPY_HIST WHERE CASE_KEY = 4468919 ORDER BY CRE_TS, FR_DATE, TO_DATE, TXN_DATE, PAY_TYPE, PAY_MTHD 
SELECT * FROM PRDDBS1.TAS_PROF_HIST WHERE CASE_KEY = 4468919 ORDER BY FR_DATE, TO_DATE, REC_TYPE 
SELECT * FROM PRDDBS1.TAS_ELG_PERD WHERE CASE_KEY = 4468919 ORDER BY CUST_KEY, REC_STS, FR_DATE 
SELECT * FROM PRDDBS1.TCS_TP_DTL WHERE CASE_KEY = 4468919
SELECT * FROM PRDDBS1.TCT_CUST WHERE CUST_KEY = 3731257 OR CUST_KEY = 3735422 OR CUST_KEY = 3735424 ORDER BY CUST_KEY
SELECT * FROM PRDDBS1.TCT_CUST_DTL WHERE CUST_KEY = 3731257 OR CUST_KEY = 3735422 OR CUST_KEY = 3735424 ORDER BY CUST_KEY
SELECT * FROM PRDDBS1.TMS_PT_GEN_SDL ORDER BY SCHM_TYPE, YR, MTH, PAY_DAY, HSBC_GRP_IND 
SELECT * FROM PRDDBS1.TPY_PAY_INSTR WHERE CASE_KEY = 4468919 ORDER BY GRT_TYPE, PAY_TYPE, FR_DATE, TO_DATE, REC_STS
SELECT * FROM PRDDBS1.TMS_PAY_EST WHERE CASE_KEY = 4468919 ORDER BY GRT_TYPE, PAY_DATE, FR_DATE
SELECT * FROM PRDDBS1.TCS_CSSA WHERE CASE_KEY = 4468919